image:
  file: .gitpod/Dockerfile

# See: https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: >
      mkdir -p /workspace/opt-pulumi &&
      sudo ln -s /workspace/opt-pulumi $HOME/.pulumi-dev
    init: >
      curl -fsSL https://get.pulumi.com | sh
    command: pulumi version

vscode:
  extensions:
    - ms-python.python
    - ms-python.black-formatter
    - donjayamanne.python-extension-pack

# See: https://www.gitpod.io/docs/prebuilds/#configure-the-github-app
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
